# Copyright (c) 2026 Huraira Maqbool
# All Rights Reserved

"""
app/agent/claim_verification.py
-------------------------------
Verifies claims generated by the LLM before they are surfaced to the user.

4-Layer Grounding Architecture:
Layer 1 — Repo Scope Lock: Hard-gate. Rejects immediately if the LLM hallucinates a `repo_id` that does not match the active active repository scope. No exceptions.
Layer 2 — Lexical Grounding Check: Hard-minimum check. Demands a baseline keyword overlap between the claim and the cited chunk (excluding stopwords). Claims with zero overlap are rejected.
Layer 3 — Semantic Similarity: Supporting signal used to evaluate valid paraphrased claims that pass the Layer 2 minimum but may have low lexical scores.
Layer 4 — Confidence Scoring: Computed by combining Layer 2 (40%) and Layer 3 (60%). Claims falling below the minimum threshold are honestly abstained rather than surfacing fabricated citations.
"""
from __future__ import annotations

import json
import math
import re
import time
from typing import Any

from app.agent.confidence import (
    check_file_existence,
    check_line_bounds,
    path_key,
)
from app.agent.grounding import (
    is_abstention_claim,
    is_factual_claim,
    normalize_citation,
    normalize_claim,
    strip_json_fences,
)
from app.retrieval.source_priority import is_test_path, is_src_path, chunk_path as _chunk_path_key
from app.config import settings
from app.observability.logging_config import logger


def _cosine_similarity(a: list[float], b: list[float]) -> float:
    if not a or not b or len(a) != len(b):
        return 0.0
    dot = sum(x * y for x, y in zip(a, b))
    na = math.sqrt(sum(x * x for x in a))
    nb = math.sqrt(sum(y * y for y in b))
    if na == 0.0 or nb == 0.0:
        return 0.0
    return max(0.0, min(1.0, dot / (na * nb)))


def _hit_path(hit: dict[str, Any]) -> str:
    meta = hit.get("chunk_metadata") or hit
    return path_key(str(meta.get("display_path") or meta.get("file_path") or ""))


def _hit_text(hit: dict[str, Any]) -> str:
    meta = hit.get("chunk_metadata") or hit
    return str(hit.get("chunk") or hit.get("snippet") or meta.get("chunk") or meta.get("snippet") or "")


def _retrieval_text_for_citation(
    norm_path: str,
    start_line: int,
    end_line: int,
    retrieval_hits: list[dict[str, Any]] | None,
    *,
    path_only: bool = False,
) -> str:
    """Pick best chunk text from live retrieval hits (overlap first, then path match)."""
    best_overlap = 0
    best_text = ""
    path_fallback = ""
    best_score = -1.0
    for hit in retrieval_hits or []:
        hp = _hit_path(hit)
        if hp != norm_path:
            continue
        text = _hit_text(hit).strip()
        if not text:
            continue
        if path_only:
            hit_score = float(hit.get("score") or 0.0)
            if hit_score > best_score:
                best_score = hit_score
                path_fallback = text
            continue
        meta = hit.get("chunk_metadata") or hit
        cs = int(meta.get("start_line") or 0)
        ce = int(meta.get("end_line") or cs)
        if cs < 1:
            continue
        overlap = max(0, min(end_line, ce) - max(start_line, cs) + 1)
        if overlap > best_overlap:
            best_overlap = overlap
            best_text = text
    chosen = best_text or path_fallback
    return chosen[: settings.CITED_TEXT_MAX_CHARS] if chosen else ""


def fetch_cited_text(
    repo_id: str,
    file_path: str,
    start_line: int,
    end_line: int,
    *,
    retrieval_hits: list[dict[str, Any]] | None = None,
) -> str:
    """Read cited lines from clone, else overlapping chunk metadata / retrieval hits."""
    from app.agent.confidence import _clone_file_path, _load_repo_metadata, _normalize_repo_path

    norm = path_key(file_path)
    s = max(1, int(start_line))
    e = max(s, int(end_line))

    # Ground claims against retrieval hits first — LLM line numbers are often approximate.
    if retrieval_hits:
        from_hits = _retrieval_text_for_citation(norm, s, e, retrieval_hits)
        if from_hits:
            return from_hits
        path_only = _retrieval_text_for_citation(norm, s, e, retrieval_hits, path_only=True)
        if path_only:
            return path_only

    abs_path = _clone_file_path(repo_id, _normalize_repo_path(file_path))
    if abs_path is not None and abs_path.is_file():
        try:
            lines = abs_path.read_text(encoding="utf-8", errors="replace").splitlines()
            e = min(len(lines), e)
            if s <= e:
                return "\n".join(lines[s - 1 : e])
        except OSError as exc:
            logger.debug(
                "claim_verify_clone_read_failed",
                repo_id=repo_id,
                file_path=file_path,
                error=str(exc),
            )

    best_overlap = 0
    best_text = ""
    for meta in _load_repo_metadata(repo_id):
        meta_path = path_key(
            str(meta.get("display_path") or meta.get("file_path") or meta.get("normalized_path") or "")
        )
        if meta_path != norm:
            continue
        chunk_start = int(meta.get("start_line") or 0)
        chunk_end = int(meta.get("end_line") or chunk_start)
        overlap = max(0, min(e, chunk_end) - max(s, chunk_start) + 1)
        if overlap > best_overlap:
            best_overlap = overlap
            best_text = str(meta.get("chunk") or meta.get("snippet") or "")

    if best_text:
        return best_text[: settings.CITED_TEXT_MAX_CHARS]

    return ""


_COMMON_PROGRAMMING_WORDS: frozenset[str] = frozenset({
    "class", "def", "import", "from", "return", "yield", "raise", "try", "except", "finally",
    "assert", "global", "nonlocal", "lambda", "with", "as", "if", "elif", "else", "while",
    "for", "break", "continue", "pass", "in", "is", "not", "and", "or", "true", "false", "none",
    "defined", "defines", "definition", "implemented", "implements", "implementation",
    "called", "calls", "used", "uses", "using", "method", "function", "func", "module",
    "package", "file", "filepath", "code", "codebase", "feature", "logic", "flow", "process",
    "system", "loader", "load", "loads", "loading", "save", "saves", "saving", "stored",
    "store", "stores", "storing", "check", "checks", "checking", "the", "are", "this",
    "that", "been", "have", "has", "had", "does", "done", "doing", "will", "would", "shall",
    "should", "can", "could", "may", "might", "must", "how", "what", "where", "when", "why",
    "which", "who", "whom", "whose", "about", "above", "after", "again", "against", "all",
    "any", "both", "each", "few", "more", "most", "other", "some", "such", "than", "too",
    "very", "just", "only", "also", "here", "there", "then", "once", "hereby", "thereby",
    "library", "project", "context", "variable", "object", "instance", "argument", "parameter",
    "type", "value", "string", "number", "boolean", "list", "dict", "tuple", "set", "write",
    "read", "print", "output", "input", "error", "exception", "caller", "callee",
    "session", "sessions", "request", "requests", "response", "responses", "http", "https",
    "send", "sends", "sent", "sending", "prepare", "prepares", "prepared", "preparing",
    "construct", "constructs", "constructed", "constructing", "connection", "connections",
    "client", "clients", "header", "headers", "auth", "token", "tokens", "data", "json",
    "text", "url", "urls", "make", "makes", "made", "making", "handler", "handlers",
    "handle", "handles", "handled", "handling", "call", "calls", "called", "calling",
    "parameter", "parameters", "argument", "arguments", "object", "objects", "variable",
    "variables", "value", "values"
})


def _lexical_overlap_score(claim: str, cited_text: str) -> float:
    """Token overlap — natural-language claims vs code often score low on embeddings alone."""
    claim_tokens = {
        t for t in re.findall(r"[a-zA-Z_][\w]*", claim.lower()) if len(t) > 2
    }
    claim_tokens = {t for t in claim_tokens if t not in _COMMON_PROGRAMMING_WORDS}

    code_tokens = {
        t for t in re.findall(r"[a-zA-Z_][\w]*", cited_text.lower()) if len(t) > 2
    }
    code_tokens = {t for t in code_tokens if t not in _COMMON_PROGRAMMING_WORDS}

    if not claim_tokens:
        return 0.0
    return len(claim_tokens & code_tokens) / len(claim_tokens)


def _line_range_ok(
    citation: dict[str, Any],
    repo_id: str,
    *,
    allowed_paths: set[str] | None = None,
    retrieval_hits: list[dict[str, Any]] | None = None,
) -> bool:
    """True when cited lines overlap an indexed chunk or pass strict bounds."""
    from app.agent.confidence import (
        _load_repo_metadata,
        path_key,
    )

    cite = {**citation, "repo_id": repo_id, "function_name": None, "unparseable": False}
    if check_line_bounds(cite):
        return True

    path = path_key(str(citation.get("file_path", "")))
    start = int(citation.get("start_line") or 0)
    end = int(citation.get("end_line") or start)
    if not path or start < 1:
        return False

    for meta in _load_repo_metadata(repo_id):
        meta_path = path_key(
            str(meta.get("display_path") or meta.get("file_path") or meta.get("normalized_path") or "")
        )
        if meta_path != path:
            continue
        cs = int(meta.get("start_line") or 0)
        ce = int(meta.get("end_line") or cs)
        if start <= ce and end >= cs:
            return True

    for hit in retrieval_hits or []:
        hp = _hit_path(hit)
        if hp != path:
            continue
        meta = hit.get("chunk_metadata") or hit
        cs = int(meta.get("start_line") or 0)
        ce = int(meta.get("end_line") or cs)
        if cs >= 1 and start <= ce and end >= cs:
            return True

    if allowed_paths and path in allowed_paths:
        return True

    return False


def _structural_ok(
    citation: dict[str, Any],
    repo_id: str,
    *,
    allowed_paths: set[str] | None = None,
    retrieval_hits: list[dict[str, Any]] | None = None,
) -> bool:
    citation = normalize_citation(citation)
    if not isinstance(citation, dict):
        return False
        
    # Layer 1: Repo Scope Lock (reject immediately if cited chunk's repo_id != active repo_id)
    cited_repo_id = citation.get("repo_id")
    if cited_repo_id and cited_repo_id != repo_id:
        logger.warning("claim_verify_layer1_fail", claim_repo=cited_repo_id, active_repo=repo_id)
        return False
        
    from app.agent.confidence import path_key

    raw_path = str(citation.get("file_path", ""))
    if is_test_path(raw_path) and retrieval_hits:
        src_available = any(
            is_src_path(_chunk_path_key(h if isinstance(h, dict) else {}))
            for h in retrieval_hits
        )
        if src_available:
            return False
    pk = path_key(raw_path)
    cite = {
        **citation,
        "file_path": _normalize_repo_path(raw_path),
        "repo_id": repo_id,
        "function_name": None,
        "unparseable": False,
    }
    path_ok = (
        check_file_existence(cite)
        or (allowed_paths is not None and pk in allowed_paths)
    )
    lines_ok = _line_range_ok(
        citation,
        repo_id,
        allowed_paths=allowed_paths,
        retrieval_hits=retrieval_hits,
    )
    return path_ok and lines_ok


def _log_verify_check(
    *,
    repo_id: str,
    claim_index: int,
    claim_text: str,
    citation: dict[str, Any] | None,
    structural_ok: bool,
    cited_text_len: int,
    supported: bool | None,
    method: str,
    similarity: float | None = None,
    lookup_note: str = "",
) -> None:
    logger.info(
        "claim_verify_check",
        repo_id=repo_id,
        claim_index=claim_index,
        claim_preview=(claim_text or "")[:120],
        citation_file=citation.get("file_path") if citation else None,
        citation_lines=(
            f"{citation.get('start_line')}-{citation.get('end_line')}"
            if citation and citation.get("start_line")
            else None
        ),
        structural_ok=structural_ok,
        cited_text_len=cited_text_len,
        supported=supported,
        method=method,
        similarity=similarity,
        lookup_note=lookup_note,
    )


def _normalize_repo_path(path: str) -> str:
    from app.agent.confidence import _normalize_repo_path as _nrp
    return _nrp(path)


def _verify_embedding_batch(
    pairs: list[tuple[str, str]],
) -> tuple[list[float], str | None]:
    """Return cosine similarity for each (claim, cited_text) pair."""
    if not pairs:
        return [], None
    try:
        from app.retrieval.embeddings import embed_batch

        texts = [p[0] for p in pairs] + [p[1] for p in pairs]
        vectors = embed_batch(texts)
        n = len(pairs)
        scores: list[float] = []
        for i in range(n):
            scores.append(_cosine_similarity(vectors[i], vectors[n + i]))
        return scores, None
    except Exception as exc:
        logger.error("claim_embed_verify_failed", error=str(exc))
        return [0.0] * len(pairs), str(exc)


def _check_ast_symbol_grounding(claim_text: str, repo_id: str, cited_file_path: str, cited_text: str) -> str:
    """
    Deterministic AST structural gate (Replaces LLM entailment).
    Extracts named entities from the claim and verifies they exist as AST symbols in the cited chunk.
    """
    print(f"[DEBUG] Enter _check_ast_symbol_grounding: claim={claim_text[:30]}..., repo_id={repo_id}, file={cited_file_path}")
    import re
    # Extract entities: CamelCase, snake_case
    # Strict entity extraction (fixing Q15 co-occurrence)
    candidates = _get_verified_technical_entities(claim_text, repo_id)
    if not candidates:
        return "NO_CANDIDATES"

        
    from app.parsing.tree_sitter_parser import get_parser, language_for_path
    
    lang = language_for_path(cited_file_path) or "python"
    parser = get_parser(lang)
    
    if parser:
        try:
            tree = parser.parse(cited_text.encode("utf-8"))
            
            def get_identifiers(node):
                ids = set()
                if node.type in ("identifier", "property_identifier", "type_identifier"):
                    try:
                        ids.add(node.text.decode("utf-8", errors="replace"))
                    except Exception:
                        pass
                for child in node.children:
                    ids.update(get_identifiers(child))
                return ids
                
            chunk_identifiers = get_identifiers(tree.root_node)
            # Require all candidate identifiers to be present in the chunk
            all_match = all(cand in chunk_identifiers for cand in candidates)
            if all_match:
                print("[DEBUG] _check_ast_symbol_grounding: SUCCESS (all candidates matched)")
                return "PASS"
            
            # Log missing candidates for debugging
            missing = [cand for cand in candidates if cand not in chunk_identifiers]
            logger.warning(
                "ast_symbol_grounding_failed",
                repo_id=repo_id,
                claim=claim_text,
                file_path=cited_file_path,
                missing_candidates=missing,
            )
            return "FAIL"
        except Exception as exc:
            logger.warning("ast_symbol_grounding_parse_error", error=str(exc))
            # Fall through to raw text fallback
            
    # Fallback to regex if parser fails or is unavailable
    all_match_regex = True
    for cand in candidates:
        if not re.search(rf"\b{re.escape(cand)}\b", cited_text):
            all_match_regex = False
            break
            
    if all_match_regex:
        print("[DEBUG] _check_ast_symbol_grounding: SUCCESS (all regex matched)")
        return "PASS"
            
    logger.warning(
        "ast_symbol_grounding_regex_failed",
        repo_id=repo_id,
        claim=claim_text,
        file_path=cited_file_path,
        missing_candidates=candidates
    )
    print("[DEBUG] _check_ast_symbol_grounding: FAILURE (no match)")
    return "FAIL"

def _check_literal_grounding(claim_text: str, cited_text: str) -> bool:
    """
    Layer 7: Literal Grounding Check.
    If a claim specifically mentions numbers (e.g. status codes) or specific boolean/null literals, 
    ensure they are physically present in the cited chunk to prevent numeric/behavioral hallucinations.
    """
    import re
    
    # Extract numbers and specific keywords
    literals = set(re.findall(r"\b\d+\b", claim_text))
    literals |= set(re.findall(r"\b(?:None|True|False|null|undefined)\b", claim_text))
    
    for literal in literals:
        if not re.search(rf"\b{literal}\b", cited_text):
            logger.warning("literal_grounding_failed", claim=claim_text, missing_literal=literal)
            return False
            
    return True

def _get_verified_technical_entities(claim_text: str, repo_id: str) -> set[str]:
    """
    Restricts entity extraction to identifiers that actually resolve to real symbols
    in the codebase's symbol table, excluding common English words or arbitrary technical-sounding words.
    """
    import re
    from app.graph.builder import get_graph
    
    candidates = set(re.findall(r"\b(?:[A-Z][a-zA-Z0-9_]+|[a-z]+_[a-z0-9_]+|[a-zA-Z_][a-zA-Z0-9_]{3,})\b", claim_text))
    candidates = {c for c in candidates if c.lower() not in _COMMON_PROGRAMMING_WORDS}
    print(f"DEBUG candidates for {claim_text[:20]}...: {candidates}")
    
    graph = get_graph(repo_id)
    verified = set()
    if graph:
        for node, data in graph.nodes(data=True):
            name = data.get("name", "")
            if not name: continue
            for cand in candidates:
                if cand == name or name.endswith("." + cand):
                    verified.add(cand)
    return verified

def _check_math_formula_grounding(claim_text: str, cited_text: str) -> bool:
    """
    Layer 8: AST Mathematical Expression Grounding
    Ensures that if a mathematical formula is claimed, the operands structurally exist 
    together in an AST arithmetic expression, rather than just co-occurring randomly.
    """
    import re
    from app.parsing.tree_sitter_parser import get_parser
    
    operators = {"+", "-", "*", "/", "="}
    has_op = any(op in claim_text for op in operators)
    claim_numbers = set(re.findall(r"\b\d+\b", claim_text))
    
    if not has_op or not claim_numbers:
        return True
        
    parser = get_parser("python")
    if not parser:
        return True
        
    tree = parser.parse(cited_text.encode("utf-8"))
    
    def get_math_expressions(node):
        exprs = []
        if node.type in ("binary_operator", "assignment"):
            def get_leafs(n):
                leafs = set()
                if n.type in ("identifier", "integer", "float"):
                    leafs.add(n.text.decode("utf-8", errors="replace"))
                for c in n.children:
                    leafs.update(get_leafs(c))
                return leafs
            exprs.append(get_leafs(node))
        for child in node.children:
            exprs.extend(get_math_expressions(child))
        return exprs
        
    ast_exprs = get_math_expressions(tree.root_node)
    
    if not ast_exprs:
        logger.warning("math_formula_grounding_failed_no_ast_math", claim=claim_text)
        return False
        
    for num in claim_numbers:
        num_found_in_expr = False
        for expr_leafs in ast_exprs:
            if num in expr_leafs or f"{num}.0" in expr_leafs:
                claim_vars = set(re.findall(r"\b(?:[a-z]+_[a-z0-9_]+)\b", claim_text))
                if claim_vars:
                    if any(v in expr_leafs for v in claim_vars):
                        num_found_in_expr = True
                        break
                else:
                    num_found_in_expr = True
                    break
        if not num_found_in_expr:
            logger.warning("math_formula_grounding_failed_mismatch", claim=claim_text, num=num)
            return False
            
    return True

def _check_relationship_grounding(claim_text: str, repo_id: str, cited_text: str) -> bool:
    """
    Layer 6: Relationship Verification Check.
    If a claim asserts a functional relationship between symbols, ensure they are connected in the call graph.
    """
    import re
    from app.graph.builder import get_graph
    
    claim_lower = claim_text.lower()
    relationship_verbs = {"calls", "called", "calling", "depends on", "uses", "using", "invokes", "handled in", "communicates with"}
    
    if not any(verb in claim_lower for verb in relationship_verbs):
        return True
        
    candidates = _get_verified_technical_entities(claim_text, repo_id)
    candidates = list(candidates)
    if len(candidates) < 2:
        return True
        
    graph = get_graph(repo_id)
    if not graph:
        return False
        
    # Map candidates to graph nodes
    cand_nodes = {}
    for node, data in graph.nodes(data=True):
        name = data.get("name", "")
        for cand in candidates:
            if name == cand or name.endswith("." + cand):
                cand_nodes.setdefault(cand, set()).add(node)
                
    # If a candidate is neither in the graph nor in the cited text, it's a hallucination
    for cand in candidates:
        cand_in_graph = cand in cand_nodes
        cand_in_chunk = bool(re.search(rf"\b{re.escape(cand)}\b", cited_text))
        if not cand_in_graph and not cand_in_chunk:
            logger.warning("relationship_grounding_hallucinated_symbol", repo_id=repo_id, claim=claim_text, symbol=cand)
            return False
            
    mapped_cands = [c for c in candidates if c in cand_nodes]
    if len(mapped_cands) < 2:
        # Require at least two symbols to be actual graph nodes to verify their relationship
        return True
        
    import networkx as nx
    
    # Check if there's any connectivity between the mapped node sets
    for i in range(len(mapped_cands)):
        for j in range(i + 1, len(mapped_cands)):
            cand_a = mapped_cands[i]
            cand_b = mapped_cands[j]
            nodes_a = cand_nodes[cand_a]
            nodes_b = cand_nodes[cand_b]
            
            for na in nodes_a:
                for nb in nodes_b:
                    if na == nb:
                        return True
                    # Check if they share the same file
                    if graph.nodes[na].get("path") == graph.nodes[nb].get("path"):
                        return True
                    # Check directed edges (call graph)
                    if graph.has_edge(na, nb) or graph.has_edge(nb, na):
                        return True
                    # Check common parent (called by same function)
                    if set(graph.predecessors(na)) & set(graph.predecessors(nb)):
                        return True
                        
    logger.warning("relationship_grounding_failed", repo_id=repo_id, claim=claim_text, mapped_cands=mapped_cands)
    return False



def check_claim_symbol_definition(claim_text: str, repo_id: str, cited_file_path: str) -> bool:
    """
    Verify that if a claim asserts the definition/location of a symbol,
    the symbol actually resolves to the cited file path in this repository.
    """
    claim_lower = claim_text.lower()
    # Check if the claim implies defining or implementing a class/function/feature
    is_definition_claim = any(
        w in claim_lower
        for w in ("defined", "defines", "definition", "implemented", "implements", "implementation")
    )
    if not is_definition_claim:
        return True

    # If negative claim (not defined, not implemented, doesn't exist), bypass validation
    if "not defined" in claim_lower or "not implemented" in claim_lower or "does not" in claim_lower or "doesn't" in claim_lower:
        return True

    # Find all words that look like class names (CamelCase) or function names (snake_case)
    candidates = re.findall(r"\b(?:[A-Z][a-zA-Z0-9_]+|[a-z0-9_]+_[a-z0-9_]+)\b", claim_text)
    if not candidates:
        return True

    from app.agent.symbol_lookup import resolve_symbol_location
    from app.agent.confidence import path_key

    norm_cited = path_key(cited_file_path)

    for sym in candidates:
        # Check class first, then function
        loc_class = resolve_symbol_location(repo_id, sym, kind="class")
        loc_func = resolve_symbol_location(repo_id, sym, kind="function")
        
        # If the symbol is found in the repository
        if loc_class or loc_func:
            resolved_paths = []
            if loc_class:
                resolved_paths.append(path_key(loc_class["file_path"]))
            if loc_func:
                resolved_paths.append(path_key(loc_func["file_path"]))
            
            # Mismatch if the cited file path is not among the actual definition paths
            if norm_cited not in resolved_paths:
                logger.warning(
                    "claim_verify_symbol_mismatch",
                    repo_id=repo_id,
                    symbol=sym,
                    cited_path=cited_file_path,
                    resolved_paths=resolved_paths
                )
                return False
        else:
            # If the symbol is NOT defined in the repository, but the claim asserts it is defined,
            # this is a hallucinated nonexistent symbol
            if len(sym) >= 5 and sym not in ("fastapi", "pytest", "celery", "python"):
                logger.warning(
                    "claim_verify_nonexistent_symbol",
                    repo_id=repo_id,
                    symbol=sym,
                    cited_path=cited_file_path
                )
                return False

def check_claim_keywords_present(claim_text: str, cited_text: str) -> bool:
    """
    Ensure that specific nouns/keywords mentioned in the claim are actually
    present in the cited code snippet (case-insensitive).
    """
    claim_lower = claim_text.lower()
    
    # If negative claim (absence), bypass validation
    if "not " in claim_lower or "no " in claim_lower or "never" in claim_lower or "doesn't" in claim_lower or "does not" in claim_lower:
        return True

    # Find all words of length >= 4
    words = re.findall(r"\b[a-zA-Z]{4,}\b", claim_lower)
    
    # Filter out common programming words and stopwords
    specific_words = [w for w in words if w not in _COMMON_PROGRAMMING_WORDS]
    
    if not specific_words:
        return True

    cited_lower = cited_text.lower()
    for w in specific_words:
        # Check if the 4-character stem is present in the cited text
        stem = w[:4]
        if stem not in cited_lower:
            logger.warning(
                "claim_verify_keyword_absent",
                keyword=w,
                stem=stem,
                claim=claim_text
            )

def _check_claim_responsiveness(claim: str, question: str) -> str:
    """
    Layer 9: Responsiveness Check.
    If a user asked a specific question, verify that the factual claim
    is actually responsive to the question.
    """
    print(f"[DEBUG] Enter _check_claim_responsiveness: claim={claim[:30]}..., question={question[:30]}...")
    if not claim or not question:
        return "YES" # Default open if missing data
        
    from app.agent.llm_client import get_llm_client
    
    llm = get_llm_client()
    prompt = f"""You are a strict relevance judge.
Determine if the 'Factual Claim' directly answers or contributes to answering the 'Question'.

EXAMPLES:
Question: What is the exact mathematical formula used in the reciprocal rank fusion algorithm?
Factual Claim: The formula used is (1.0 / (rank + 60.0)).
Verdict: YES

Question: Give me a step-by-step walkthrough of how the user's question gets classified.
Factual Claim: The finalize_system_prompt function returns a system prompt with a specific instruction based on the user's question.
Verdict: NO

Question: How does the agent fetch credentials?
Factual Claim: The AgentConfig class handles environment variables.
Verdict: NO

Question: {question}
Factual Claim: {claim}
Verdict: """

    for attempt in range(2):
        try:
            res = llm.create(
                system="You are a strict relevance judge. Reply only with YES or NO.",
                messages=[{"role": "user", "content": prompt}],
                max_tokens=5
            )
            answer = "".join(b.get("text", "") for b in res.content if b.get("type") == "text").strip().upper()
            print(f"[DEBUG] LLM response raw answer: {answer}")
            if "NO" in answer and "YES" not in answer:
                print("[DEBUG] _check_claim_responsiveness: returning NO")
                return "NO"
            print("[DEBUG] _check_claim_responsiveness: returning YES")
            return "YES"
        except Exception as exc:
            import time
            logger.warning("responsiveness_check_failed", error=str(exc), attempt=attempt)
            if attempt < 1:
                time.sleep(2.0)
            else:
                return "API_FAIL"
    return "API_FAIL"


def verify_claims_batch(
    claims: list[dict[str, Any]],
    repo_id: str,
    *,
    retrieval_hits: list[dict[str, Any]] | None = None,
    allowed_paths: set[str] | None = None,
    question: str | None = None,
) -> dict[str, Any]:
    """
    Verify all claims in one batched pass.

    Returns:
        {
          "results": [{index, supported, structural_ok, similarity, method}, ...],
          "verified_count": int,
          "factual_count": int,
          "latency_ms": float,
        }
    """
    t0 = time.perf_counter()
    try:
        return _verify_claims_batch_inner(
            claims,
            repo_id,
            retrieval_hits=retrieval_hits,
            allowed_paths=allowed_paths,
            question=question,
            t0=t0,
        )
    except Exception as exc:
        import traceback

        logger.error(
            "verify_system_error",
            repo_id=repo_id,
            phase="claim_batch_exception",
            error=str(exc),
            traceback=traceback.format_exc(),
        )
        return {
            "results": [],
            "verified_count": 0,
            "factual_count": 0,
            "latency_ms": round((time.perf_counter() - t0) * 1000, 1),
            "verification_error": True,
            "error": str(exc),
        }


def _verify_claims_batch_inner(
    claims: list[dict[str, Any]],
    repo_id: str,
    *,
    retrieval_hits: list[dict[str, Any]] | None = None,
    allowed_paths: set[str] | None = None,
    question: str | None = None,
    t0: float,
) -> dict[str, Any]:
    normalized_claims: list[dict[str, Any]] = []
    for raw in claims:
        if isinstance(raw, dict):
            normalized = normalize_claim(raw)
            normalized_claims.append(
                normalized
                if normalized is not None
                else {"claim": str(raw.get("claim") or raw.get("text") or ""), "citation": None}
            )
        else:
            normalized_claims.append({"claim": "", "citation": None})
    claims = normalized_claims

    threshold = float(getattr(settings, "CLAIM_EMBED_THRESHOLD", 0.40))
    borderline_low = threshold - settings.CLAIM_EMBED_BORDERLINE_MARGIN
    lexical_threshold = float(getattr(settings, "CLAIM_LEXICAL_THRESHOLD", 0.18))
    use_llm = bool(getattr(settings, "CLAIM_VERIFY_LLM_BATCH", False))

    results: list[dict[str, Any]] = []
    embed_pairs: list[tuple[str, str]] = []
    embed_indices: list[int] = []
    llm_items: list[dict[str, Any]] = []
    llm_indices: list[int] = []
    cited_text_lens: dict[int, int] = {}

    for i, claim in enumerate(claims):
        if is_abstention_claim(claim):
            results.append({
                "index": i,
                "supported": True,
                "structural_ok": True,
                "similarity": None,
                "method": "abstention",
            })
            continue

        citation = normalize_citation(claim.get("citation"))
        if not citation:
            results.append({
                "index": i,
                "supported": False,
                "structural_ok": False,
                "similarity": None,
                "method": "missing_citation",
            })
            continue

        claim["citation"] = citation
        structural = _structural_ok(
            citation,
            repo_id,
            allowed_paths=allowed_paths,
            retrieval_hits=retrieval_hits,
        )
        if not structural:
            results.append({
                "index": i,
                "supported": False,
                "structural_ok": False,
                "similarity": None,
                "method": "structural_fail",
            })
            continue

        if not check_claim_symbol_definition(str(claim.get("claim") or ""), repo_id, citation["file_path"]):
            results.append({
                "index": i,
                "supported": False,
                "structural_ok": True,
                "similarity": 0.0,
                "method": "symbol_mismatch",
            })
            continue

        cite_start = int(citation["start_line"])
        cite_end = int(citation.get("end_line") or cite_start)
        cited_text = fetch_cited_text(
            repo_id,
            citation["file_path"],
            cite_start,
            cite_end,
            retrieval_hits=retrieval_hits,
        )
        if not cited_text.strip():
            cited_text = _retrieval_text_for_citation(
                path_key(str(citation.get("file_path", ""))),
                cite_start,
                cite_end,
                retrieval_hits,
                path_only=True,
            )
        if not cited_text.strip():
            results.append({
                "index": i,
                "supported": False,
                "structural_ok": True,
                "similarity": 0.0,
                "method": "empty_cited_text",
            })
            continue

        claim_text = str(claim.get("claim") or "")
        lex_score = _lexical_overlap_score(claim_text, cited_text)
        
        # Layer 2: Lexical Grounding Check (Hard Minimum)
        if lex_score < 0.05:
            results.append({
                "index": i,
                "supported": False,
                "structural_ok": True,
                "similarity": 0.0,
                "method": "lexical_hard_fail",
                "lexical_score": lex_score,
            })
            continue

        cited_text_lens[i] = len(cited_text)
        embed_pairs.append((claim_text, cited_text))
        embed_indices.append(i)
        results.append({
            "index": i,
            "supported": False,
            "structural_ok": True,
            "similarity": None,
            "method": "pending",
            "_cited_text": cited_text,
            "lexical_score": lex_score,
        })

    # Embedding batch — on failure fall back to lexical overlap instead of hard-gating chat.
    scores, embed_error = _verify_embedding_batch(embed_pairs)
    if embed_error is not None and embed_pairs:
        logger.warning(
            "claim_embed_batch_degraded",
            repo_id=repo_id,
            phase="claim_embed_batch",
            error=embed_error,
            pair_count=len(embed_pairs),
        )
        scores = [0.0] * len(embed_pairs)
    for claim_idx, sim in zip(embed_indices, scores):
        row = next(r for r in results if r["index"] == claim_idx)
        row["similarity"] = round(sim, 4)
        
        lex_score = row.get("lexical_score", 0.0)
        
        # Layer 4: Confidence Score (Layer 2 + Layer 3)
        confidence = (lex_score * 0.4) + (sim * 0.6)
        row["confidence_score"] = round(confidence, 4)
        
        if confidence >= threshold:
            row["supported"] = True
            row["method"] = "confidence_score"
        elif retrieval_hits:
            # Best-effort reroute...
            cited_text = row.get("_cited_text", "")
            claim_text = str(claims[claim_idx].get("claim") or "")
            pk = path_key(str(claims[claim_idx].get("citation", {}).get("file_path", "")))
            
            best_conf = confidence
            best_sim = sim
            best_text = cited_text
            for hit in retrieval_hits:
                if _hit_path(hit) != pk:
                    continue
                alt = _hit_text(hit).strip()
                if not alt or alt == cited_text:
                    continue
                alt_lex = _lexical_overlap_score(claim_text, alt)
                if alt_lex < 0.05:
                    continue # Layer 2 hard minimum
                alt_scores, _ = _verify_embedding_batch([(claim_text, alt)])
                alt_sim = alt_scores[0] if alt_scores else 0.0
                alt_conf = (alt_lex * 0.4) + (alt_sim * 0.6)
                if alt_conf > best_conf:
                    best_conf = alt_conf
                    best_sim = alt_sim
                    best_text = alt
                    
            if best_conf >= threshold:
                row["similarity"] = round(best_sim, 4)
                row["confidence_score"] = round(best_conf, 4)
                row["supported"] = True
                row["method"] = "confidence_reroute"
                row["_cited_text"] = best_text
            else:
                row["supported"] = False
                row["method"] = "confidence_fail"
        else:
            row["supported"] = False
            row["method"] = "confidence_fail"

    # Layer 5: AST Symbol Grounding Check (Replaces LLM Entailment)
    ast_items = []
    ast_indices = []
    for row in results:
        if row.get("supported") and row.get("method") not in ("abstention", "pending"):
            idx = row["index"]
            ast_items.append({
                "claim": str(claims[idx].get("claim") or ""),
                "cited_text": row.get("_cited_text", ""),
                "file_path": claims[idx].get("citation", {}).get("file_path", ""),
                "repo_id": repo_id,
            })
            ast_indices.append(idx)

    if ast_items:
        ast_supported = []
        for claim_idx, item in zip(ast_indices, ast_items):
            # Layer 5: Symbol presence
            ast_result = _check_ast_symbol_grounding(
                item["claim"], item["repo_id"], item["file_path"], item["cited_text"]
            )
            is_grounded = (ast_result == "PASS")
            if ast_result == "NO_CANDIDATES":
                row = next(r for r in results if r["index"] == claim_idx)
                if row.get("confidence_score", 0.0) >= threshold + 0.15:
                    is_grounded = True
                    item["fail_method"] = "ast_grounding_no_candidates_fallback"
                else:
                    is_grounded = False
                    item["fail_method"] = "unverified_no_fallback_signal"
            elif ast_result == "FAIL":
                item["fail_method"] = "ast_grounding_fail"
            # Layer 6: Relationship verification
            if is_grounded:
                rel_grounded = _check_relationship_grounding(item["claim"], item["repo_id"], item["cited_text"])
                if not rel_grounded:
                    is_grounded = False
                    # Use a distinct method name to differentiate failures
                    item["fail_method"] = "relationship_grounding_fail"
            
            # Layer 7: Literal verification
            if is_grounded:
                lit_grounded = _check_literal_grounding(item["claim"], item["cited_text"])
                if not lit_grounded:
                    is_grounded = False
                    item["fail_method"] = "literal_grounding_fail"
            # Layer 8: Math Formula verification
            if is_grounded:
                math_grounded = _check_math_formula_grounding(item["claim"], item["cited_text"])
                if not math_grounded:
                    is_grounded = False
                    item["fail_method"] = "math_formula_grounding_fail"
            # Layer 9: Responsiveness Check (Issue 8 Fix)
            if is_grounded and question:
                resp_grounded = _check_claim_responsiveness(item["claim"], question)
                if resp_grounded == "NO":
                    is_grounded = False
                    item["fail_method"] = "non_responsive_claim"
                elif resp_grounded == "API_FAIL":
                    lex_overlap = _lexical_overlap_score(item["claim"], question)
                    if lex_overlap > 0.10:
                        item["fail_method"] = "responsiveness_fallback"
                    else:
                        is_grounded = False
                        item["fail_method"] = "responsiveness_api_fail_no_fallback"
            # Layer 10: Library Hallucination Check
            if is_grounded:
                import re
                lib_matches = re.findall(r"\b([a-zA-Z0-9_-]+)\s+(?:library|package)\b", item["claim"].lower())
                cited_lower = item["cited_text"].lower()
                for lib in lib_matches:
                    if lib not in ("the", "a", "an", "this", "that") and lib not in cited_lower:
                        is_grounded = False
                        item["fail_method"] = "hallucinated_library"
                        break
            
            if not is_grounded:
                if "fail_method" not in item:
                    item["fail_method"] = "ast_grounding_fail"
                
            ast_supported.append(is_grounded)
            
        for claim_idx, is_grounded, item in zip(ast_indices, ast_supported, ast_items):
            row = next(r for r in results if r["index"] == claim_idx)
            if not is_grounded:
                row["supported"] = False
                row["method"] = item.get("fail_method", "ast_grounding_fail")
            elif "fail_method" in item and "fallback" in item["fail_method"]:
                row["method"] = item["fail_method"]

    # Per-claim debug audit trail
    for i, claim in enumerate(claims):
        row = next((r for r in results if r["index"] == i), None)
        if not row:
            continue
        _log_verify_check(
            repo_id=repo_id,
            claim_index=i,
            claim_text=str(claim.get("claim") or ""),
            citation=claim.get("citation"),
            structural_ok=bool(row.get("structural_ok")),
            cited_text_len=cited_text_lens.get(i, 0),
            supported=row.get("supported"),
            method=str(row.get("method", "")),
            similarity=row.get("similarity"),
        )

    # Clean internal fields
    for row in results:
        row.pop("_cited_text", None)

    factual_count = sum(1 for c in claims if is_factual_claim(c))
    verified_count = sum(
        1 for r in results
        if r.get("supported") and claims[r["index"]].get("citation") is not None
        and not is_abstention_claim(claims[r["index"]])
    )

    elapsed_ms = round((time.perf_counter() - t0) * 1000, 1)
    logger.info(
        "claim_verify_batch_complete",
        repo_id=repo_id,
        factual_count=factual_count,
        verified_count=verified_count,
        latency_ms=elapsed_ms,
    )

    return {
        "results": results,
        "verified_count": verified_count,
        "factual_count": factual_count,
        "latency_ms": elapsed_ms,
    }
